import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    // ── Diataxis sections ──────────────────────────────────────
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      link: {type: 'doc', id: 'tutorials/index'},
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: 'How-To Guides',
      collapsed: false,
      link: {type: 'doc', id: 'how-to/index'},
      items: [{type: 'autogenerated', dirName: 'how-to'}],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      link: {type: 'doc', id: 'reference/index'},
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Explanation',
      collapsed: false,
      link: {type: 'doc', id: 'explanation/index'},
      items: [{type: 'autogenerated', dirName: 'explanation'}],
    },

    // ── Coverage matrices (auto-generated by `thoughtjack docs generate`) ──
    {
      type: 'category',
      label: 'Coverage',
      collapsed: false,
      link: {type: 'generated-index', description: 'Auto-generated coverage matrices.'},
      items: [{type: 'autogenerated', dirName: 'coverage'}],
    },
  ],
};

export default sidebars;
