import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Conditionally load generated scenario sidebar (git-ignored).
// The site builds fine without it — only `thoughtjack docs generate` creates sidebars.js.
let scenariosSidebar: SidebarsConfig[string] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const generated = require('./sidebars.js');
  scenariosSidebar = generated.scenariosSidebar ?? [];
} catch {
  // sidebars.js not generated yet — that's fine
}

const sidebars: SidebarsConfig = {
  docs: [
    // ── Diataxis sections ──────────────────────────────────────
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      link: {type: 'doc', id: 'tutorials/index'},
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: 'How-To Guides',
      collapsed: false,
      link: {type: 'doc', id: 'how-to/index'},
      items: [{type: 'autogenerated', dirName: 'how-to'}],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      link: {type: 'doc', id: 'reference/index'},
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Explanation',
      collapsed: false,
      link: {type: 'doc', id: 'explanation/index'},
      items: [{type: 'autogenerated', dirName: 'explanation'}],
    },

    // ── Attack Library (auto-generated) ────────────────────────
    {
      type: 'category',
      label: 'Attack Library',
      collapsed: false,
      link: {type: 'doc', id: 'scenarios/index'},
      items: [...scenariosSidebar],
    },

    // ── Coverage matrices (auto-generated) ─────────────────────
    {
      type: 'category',
      label: 'Coverage',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'coverage'}],
    },
  ],
};

export default sidebars;
