//! `ThoughtJack` - Adversarial MCP server for security testing
//!
//! This library provides components for building adversarial MCP servers
//! used in security testing scenarios.

/// Build-time metadata generated by the `built` crate.
#[allow(clippy::doc_markdown)]
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

pub mod behavior;
pub mod capture;
pub mod cli;
pub mod config;
pub mod dynamic;
pub mod error;
pub mod generator;
pub mod handlers;
pub mod observability;
pub mod phase;
pub mod server;
pub mod transport;
