//! Docusaurus sidebar generation from scenario registry.
//!
//! Generates `sidebars.js` configuration reflecting the category and
//! scenario ordering defined in `registry.yaml`.
//!
//! TJ-SPEC-011 F-004

use crate::registry::Registry;
use std::path::Path;

/// Generate Docusaurus `sidebars.js` content from a registry.
///
/// Each category becomes a sidebar group, and each scenario becomes
/// a document link within that group.
///
/// Implements: TJ-SPEC-011 F-004
#[must_use]
pub fn generate_sidebars_js(registry: &Registry) -> String {
    let mut lines = vec![
        "// AUTO-GENERATED — DO NOT EDIT".to_string(),
        "// Generated by thoughtjack docs generate".to_string(),
        String::new(),
        "/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */".to_string(),
        "const sidebars = {".to_string(),
        "  scenariosSidebar: [".to_string(),
    ];

    for category in &registry.categories {
        lines.push("    {".to_string());
        lines.push("      type: 'category',".to_string());
        lines.push(format!(
            "      label: '{}',",
            escape_js_string(&category.name)
        ));
        lines.push("      items: [".to_string());

        for scenario_path in &category.scenarios {
            let doc_id = scenario_path_to_doc_id(scenario_path);
            lines.push(format!("        'scenarios/{doc_id}',"));
        }

        lines.push("      ],".to_string());
        lines.push("    },".to_string());
    }

    lines.push("  ],".to_string());
    lines.push("};".to_string());
    lines.push(String::new());
    lines.push("module.exports = sidebars;".to_string());

    lines.join("\n")
}

/// Convert a scenario file path to a Docusaurus doc ID.
///
/// Strips `scenarios/` prefix and `.yaml`/`.yml` extension.
/// Example: `scenarios/phased/rug-pull.yaml` → `phased/rug-pull`
fn scenario_path_to_doc_id(path: &Path) -> String {
    let s = path.to_string_lossy();
    let stripped = s.strip_prefix("scenarios/").unwrap_or(&s);
    stripped
        .strip_suffix(".yaml")
        .or_else(|| stripped.strip_suffix(".yml"))
        .unwrap_or(stripped)
        .to_string()
}

/// Escape a string for JavaScript single-quoted string context.
fn escape_js_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::{Category, Registry, SiteConfig};
    use std::path::PathBuf;

    fn test_registry() -> Registry {
        Registry {
            site: SiteConfig {
                title: "Test Catalog".to_string(),
                description: "Test".to_string(),
                base_url: None,
            },
            categories: vec![
                Category {
                    id: "injection".to_string(),
                    name: "Injection Attacks".to_string(),
                    description: None,
                    order: Some(1),
                    scenarios: vec![
                        PathBuf::from("scenarios/injection/tool-response.yaml"),
                        PathBuf::from("scenarios/injection/resource.yaml"),
                    ],
                },
                Category {
                    id: "phased".to_string(),
                    name: "Phased Attacks".to_string(),
                    description: None,
                    order: Some(2),
                    scenarios: vec![PathBuf::from("scenarios/phased/rug-pull.yaml")],
                },
            ],
        }
    }

    #[test]
    fn test_generate_sidebars() {
        let registry = test_registry();
        let js = generate_sidebars_js(&registry);

        assert!(js.contains("AUTO-GENERATED"));
        assert!(js.contains("scenariosSidebar"));
        assert!(js.contains("Injection Attacks"));
        assert!(js.contains("Phased Attacks"));
        assert!(js.contains("'scenarios/injection/tool-response'"));
        assert!(js.contains("'scenarios/phased/rug-pull'"));
        assert!(js.contains("module.exports"));
    }

    #[test]
    fn test_scenario_path_to_doc_id() {
        assert_eq!(
            scenario_path_to_doc_id(Path::new("scenarios/phased/rug-pull.yaml")),
            "phased/rug-pull"
        );
        assert_eq!(
            scenario_path_to_doc_id(Path::new("scenarios/injection/tool.yml")),
            "injection/tool"
        );
        assert_eq!(
            scenario_path_to_doc_id(Path::new("custom/path.yaml")),
            "custom/path"
        );
    }

    #[test]
    fn test_escape_js_string() {
        assert_eq!(escape_js_string("hello"), "hello");
        assert_eq!(escape_js_string("it's"), "it\\'s");
        assert_eq!(escape_js_string("a\\b"), "a\\\\b");
    }
}
