//! `ThoughtJack` — Adversarial agent security testing tool
//!
//! This library provides components for building adversarial protocol servers
//! and clients used in security testing scenarios across MCP, A2A, and AG-UI.

/// Build-time metadata generated by the `built` crate.
#[allow(clippy::doc_markdown)]
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

pub mod cli;
#[cfg(feature = "docgen")]
pub mod docgen;
pub mod engine;
pub mod error;
pub mod loader;
pub mod observability;
pub mod scenarios;
pub mod transport;
pub mod verdict;
